name: El enano

on:
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Saludando:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Saludo al nuevo dev
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Bienvenido/a ${{ github.actor }}! 🚀✨😃`
              })
        env: 
          PATH_TOKEN: ${{ secrets.PERSONAL_TOKEN }} 
      - name: Incluyo el nombre en el README.md
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Nuestro enano:"
          git fetch origin main
          git checkout main
          echo -e "\n${{ github.actor }}" >> README.md
          git add README.md
          git commit -m "${{ github.actor }} acaba de aterrizar 🤩"
          git push origin main
