name: El enano

on:
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  Saludando:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Guardo el nombre
        with:
          script: |
            response=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PATH_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/${{github.actor}})
            user_name=$(echo "$response" | jq -r '.name')
            echo "NAME=$user_name" >> $GITHUB_ENV
        env: 
          PATH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      - name: Saludo al nuevo dev
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Bienvenido/a ${{ env.NAME }}! 🚀✨😃`
              })
        env: 
          PATH_TOKEN: ${{ secrets.PERSONAL_TOKEN }} 
      - name: Incluyo el nombre en el README.md
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Nuestro enano:"
          git fetch origin main
          git checkout main
          echo -e "\n${{env.NAME}}" >> README.md
          git add README.md
          git commit -m "${{env.NAME}} acaba de aterrizar 🤩"
          git push origin main
